### ISSUE TITLE
Hide toolbar

### ISSUE THREAD

**Issue by jcuenod** [wobsoriano/solid-apexcharts#11]
I see there's an option to hide the toolbar. I expected to do something like:

```
<SolidApexCharts toolbar={{ show: false }} />
```

But this has no effect. Am I doing something wrong, or is this prop not being passed down to Apex?

**Comment by wobsoriano** [comment]
I'll revisit this one, but you can set the chart toolbar options like this

```tsx
import type ApexCharts from 'apexcharts'

const [options] = createSignal<ApexChartProps['options']>({
  xaxis: {
    categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998],
  },
  chart: {
    toolbar: {
      show: false
    }
  }
})
```
