### ISSUE TITLE
unexpected token `export`

### ISSUE THREAD

**Issue by AshSimmonds** [wobsoriano/solid-apexcharts#2]
Using just the basic stuff from the readme.

![screenshot_20230107-220012_msedge_OAoGiRDseA](https://user-images.githubusercontent.com/9034041/211148577-1479df86-cbb9-4157-a006-35c3ea0492d5.png)

**Comment by wobsoriano** [comment]
Possible dup of https://github.com/wobsoriano/solid-apexcharts/issues/1
