### ISSUE TITLE
Example of polarArea chart?

### ISSUE THREAD

**Issue by kevinelliott** [wobsoriano/solid-apexcharts#3]
Do you have an example of a simple polarArea type chart?

**Comment by cheapekt** [comment]
I would like to do a phasors diagram, it's posible to do in your solid-apexcharts?

![image](https://user-images.githubusercontent.com/17901464/236383584-70ddb4d8-9992-4851-88ac-3f0c37014b22.png)

**Comment by wobsoriano** [comment]
Taken from the official [example](https://apexcharts.com/javascript-chart-demos/polar-area-charts/basic/), you can do it like this:

```tsx
function Chart() {
  const [options] = createSignal({
    stroke: {
      colors: ['#fff'],
    },
    fill: {
      opacity: 0.8,
    },
    responsive: [{
      breakpoint: 480,
      options: {
        chart: {
          width: 200,
        },
        legend: {
          position: 'bottom',
        },
      },
    }],
  });
  const [series] = createSignal([14, 23, 21, 17, 15, 10, 12, 17, 21]);

  return <SolidApexCharts type="polarArea" options={options()} series={series()} />;
}
```
