### ISSUE TITLE
Need access to ApexChartProps type

### ISSUE THREAD

**Issue by tsdevau** [wobsoriano/solid-apexcharts#4]
Can you consider adding an export for **ApexChartProps** type?

Currently as it's not exported, you basically need to re-create `/dist/index.d.ts` importing from `apexcharts` to redeclare everything in order to get access to **ApexChartProps** type to enable typings on the options store.

Would be a lot easier and cleaner just to add a type import from `solid-apexcharts`.

### example
```tsx
import { SolidApexCharts, createApexCharts, type ApexChartProps } from "solid-apexcharts"
```

then enables you to apply the prop type on the store:

```tsx
const [chartOptions] = createStore<ApexChartProps>({
    type: "area",
    series: [
      { name: "Blah Blah", type: "area", data: seriesData() },
// etc...
```

Thereby providing type access when setting up the chart options store.

**Comment by wobsoriano** [comment]
Exported in 0.3.0.
