### ISSUE TITLE
Error Chart Type

### ISSUE THREAD

**Issue by cheesycoffee** [wobsoriano/solid-apexcharts#5]
I got an error when changing type in options ` 
chart: {
      id: "solidchart-example",
      type: "radialBar",
}`

**The types of 'chart.type' are incompatible between these types.
    Type 'string' is not assignable to type '"radialBar" | "bar" | "line" | "area" | "pie" | "donut" | "scatter" | "bubble" | "heatmap" | "candlestick" | "boxPlot" | "radar" | "polarArea" | "rangeBar" | "rangeArea" | "treemap" | undefined'**

![Screenshot from 2023-09-10 22-49-58](https://github.com/wobsoriano/solid-apexcharts/assets/63185548/81412eb9-2f6c-422b-82b8-d5e3b803fac2)

**Comment by wobsoriano** [comment]
You can fix it by passing a type to the signal

```ts
import { SolidApexCharts, type ApexChartProps } from 'solid-apexcharts';

const [options] = createSignal<ApexChartProps['options']>({
  chart: {
    id: 'solidchart-example',
    type: 'radialBar'
  },
  // other opts
});
```
