### ISSUE TITLE
ApexCharts is not defined

### ISSUE THREAD

**Issue by surong630** [wobsoriano/solid-apexcharts#6]
hi,when i use SolidApexCharts type is area, progress happen Error, Error message is .
<img width="568" alt="image" src="https://github.com/wobsoriano/solid-apexcharts/assets/64485227/64b4d7ef-0156-4b35-b13c-352a7dfea75d">
code: 
`
<SolidApexCharts type='area' options={options} series={series} />
`

**Comment by wobsoriano** [comment]
Are you using solid start by any chance? Also, make sure you installed `apexcharts`.
